apiVersion: v1
kind: Service
metadata:
  name: prueba-jenkins-service
spec:
  type: NodePort
  selector:
    app: prueba-jenkins
  ports:
    - port: 9000
      targetPort: 9000
      nodePort: 30007
